ActionTypes = {
  SEARCH_BY_QUERY: 'SEARCH_BY_QUERY',
  SEARCH_BY_CATEGORY: 'SEARCH_BY_CATEGORY',
  SEARCH_BY_LANGUAGE: 'SEARCH_BY_LANGUAGE',
  SEARCH_BY_TIME_AGO: 'SEARCH_BY_TIME_AGO',
  SEARCH_BY_PRESENTATION: 'SEARCH_BY_PRESENTATION',
  SAVE_QUERY: 'SAVE_QUERY'
};
